# expects Lingoturk repository in the parent folder of the script

cd .. 
cp Lingoturk/lingoturk/public/javascripts/{resize_canvas.js,calibration.js,precision_calculation.js,webgazer.js} Thesis-Project/RefGameShapesGazeFeedbackExperiment/public__javascripts/
cp Lingoturk/lingoturk/public/javascripts/ExperimentRendering/RefGameShapesGazeFeedbackExperiment/RefGameShapesGazeFeedbackExperiment_render.js Thesis-Project/RefGameShapesGazeFeedbackExperiment/public__javascripts__ExperimentRendering/RefGameShapesGazeFeedbackExperiment/
cp Lingoturk/lingoturk/app/models/Questions/RefGameShapesGazeFeedbackExperiment/{experiment.properties,fields.json,resultQuery.sql} Thesis-Project/RefGameShapesGazeFeedbackExperiment/app__models__Questions/RefGameShapesGazeFeedbackExperiment/
cp Lingoturk/lingoturk/app/views/ExperimentRendering/RefGameShapesGazeFeedbackExperiment/RefGameShapesGazeFeedbackExperiment_render.html Thesis-Project/RefGameShapesGazeFeedbackExperiment/app__views__ExperimentRendering/RefGameShapesGazeFeedbackExperiment/RefGameShapesGazeFeedbackExperiment_render.html
cp Lingoturk/lingoturk/public/stylesheets/ExperimentRendering/RefGameShapesGazeFeedbackExperiment/RefGameShapesGazeFeedbackExperiment_render.css Thesis-Project/RefGameShapesGazeFeedbackExperiment/public__stylesheets__ExperimentRendering/RefGameShapesGazeFeedbackExperiment/RefGameShapesGazeFeedbackExperiment_render.css
cp -a Lingoturk/lingoturk/public/images/Experiments/RefGameShapesGazeFeedbackExperiment/. Thesis-Project/RefGameShapesGazeFeedbackExperiment/public__images__Experiments/RefGameShapesGazeFeedbackExperiment/
